/*!
 * `prefset export` subcommand
 *
 * I (dave) really like this feature - but we need to make damn sure that we
 * output a valid script and don't break things for people.  yes, they are in
 * charge of their own config so i don't feel totally responsible if they put
 * stupid chars in the config... but i lowkey do feel responsible so let's do
 * our best here, ok?
 */

use anyhow::Result;
use indoc::formatdoc;

use crate::State;
use crate::args::ExportCommand;
use crate::config::Config;
use crate::util::defaults;

/// `prefset export ...`
pub fn run(state: &State, _cmd: &ExportCommand) -> Result<()> {
    let config = Config::load(&state.config_path)?;
    let script = export(&config)?;

    print!("{}", script);

    Ok(())
}

/// Convert a prefset config file to a POSIX shell script
pub fn export(config: &Config) -> Result<String> {
    let name = env!("CARGO_PKG_NAME");
    let version = env!("CARGO_PKG_VERSION");

    let mut output = formatdoc! {"
        #!/bin/sh
        #
        # Apply user preferences on macOS
        #
        # Generated by {name}@{version}

        set -e
    "};

    let mut previous_domain: Option<&str> = None;

    for preference in &config.preferences {
        if previous_domain != Some(&preference.domain) {
            // put the domain on its own line as a comment
            // this is crazy but the domain can have control characters in it!!
            // lmao ask me how i know.  anyways, we escape them here and TODO
            // add tests for this
            output.push_str("\n# ");
            output.extend(preference.domain.escape_default());
            output.push('\n');

            previous_domain = Some(&preference.domain);
        }

        let cmd = defaults::write_command(preference)?;
        output.push_str(&cmd);
        output.push('\n');
    }

    Ok(output)
}
